# Generated by Django 5.0.1 on 2024-06-13 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_normalfacility_slot_frequency_and_more'),
        ('customer', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='facility',
        ),
        migrations.AddField(
            model_name='booking',
            name='sub_facility',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.normalfacility'),
            preserve_default=False,
        ),
    ]
