# Generated by Django 5.0.1 on 2024-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_booking_booking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
