# Generated by Django 5.0.6 on 2024-06-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_remove_customeruser_customuser_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_id',
        ),
    ]
