# Generated by Django 5.0.1 on 2024-06-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_userbusinesslink_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityType', models.CharField(max_length=255)),
                ('facilityName', models.CharField(max_length=255)),
                ('facilityDescription', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='business.business')),
            ],
        ),
    ]
