# Generated by Django 5.0.1 on 2024-06-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_normalfacility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalfacility',
            name='slot_frequency',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='normalfacility',
            name='slot_length',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
