# Generated by Django 5.0.1 on 2024-06-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_normalfacility_slot_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalfacility',
            name='slot_frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='normalfacility',
            name='slot_length',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='RestaurantFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('slot_frequency', models.IntegerField()),
                ('slot_length', models.IntegerField()),
                ('slot_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tables_of_1', models.PositiveIntegerField(default=0)),
                ('tables_of_2', models.PositiveIntegerField(default=0)),
                ('tables_of_3', models.PositiveIntegerField(default=0)),
                ('tables_of_4', models.PositiveIntegerField(default=0)),
                ('tables_of_5', models.PositiveIntegerField(default=0)),
                ('tables_of_6', models.PositiveIntegerField(default=0)),
                ('tables_of_7', models.PositiveIntegerField(default=0)),
                ('tables_of_8', models.PositiveIntegerField(default=0)),
                ('tables_of_9', models.PositiveIntegerField(default=0)),
                ('tables_of_10', models.PositiveIntegerField(default=0)),
                ('tables_of_11', models.PositiveIntegerField(default=0)),
                ('tables_of_12', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.facility')),
            ],
        ),
    ]
