# Generated by Django 5.0.1 on 2024-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_normalfacility_friday_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantfacility',
            name='friday_close',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='friday_open',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='monday_close',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='monday_open',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='saturday_close',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='saturday_open',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='sunday_close',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='sunday_open',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='thursday_close',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='thursday_open',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='tuesday_close',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='tuesday_open',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='wednesday_close',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantfacility',
            name='wednesday_open',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
