# Generated by Django 5.0.1 on 2024-07-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_normalfacility_slot_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('normal_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.normalfacility')),
                ('restaurant_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.restaurantfacility')),
            ],
        ),
    ]
