# Generated by Django 5.0.1 on 2024-07-30 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_activation_code_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
