# Generated by Django 5.0.1 on 2024-08-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_booking_booking_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='next_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_booking', to='customer.booking'),
        ),
    ]
