# Generated by Django 5.0.1 on 2024-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
