# Generated by Django 5.0.1 on 2024-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_booking_stripe_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
