# Generated by Django 5.0.1 on 2024-06-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('slot_frequency', models.IntegerField()),
                ('slot_length', models.IntegerField()),
                ('slot_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.facility')),
            ],
        ),
    ]
