# Generated by Django 5.0.1 on 2024-06-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_normalfacility_slot_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalfacility',
            name='additional_minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normalfacility',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
