# Generated by Django 5.0.1 on 2024-07-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_closeddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseNormalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closed', models.BooleanField(default=True)),
                ('normal_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.normalfacility')),
            ],
        ),
    ]
