# Generated by Django 5.0.1 on 2024-07-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_closenormalfacility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closenormalfacility',
            name='closed',
        ),
    ]
